### ISSUE TITLE
很多问题。尽量采用另外的三家的方式

### ISSUE THREAD

**Issue by life2nd** [90ck/CKNavSmoothDemo#4]
在滑动返回中，或者滑动一般的时候返回，很容易出现导航栏错乱的情况。研究研究可以，别用到项目中。

1、前一个导航栏标题可能不在中央
2、后一个个人中心可能显示前一个的标题，而非自己本身透明的标题
3、开始中的时候导航栏透明的突然变化也不是友好的

**Comment by 90ck** [comment]
是真机吗
